language: objective-c
osx_image: xcode7.3
# xcode_project: PopApp.xcodeproj
xcode_workspace: PopApp.xcworkspace
xcode_scheme: PopApp
xcode_sdk: iphonesimulator9.3

# https://docs.travis-ci.com/user/languages/objective-c